CREATE TABLE chatter(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(50),
  user_id BIGINT NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  updated_at TIMESTAMP ,
  updated_by VARCHAR(255),
  deleted_at TIMESTAMP,
  deleted_by VARCHAR(255)
);

CREATE TABLE chat_group(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  updated_at TIMESTAMP ,
  updated_by VARCHAR(255),
  deleted_at TIMESTAMP,
  deleted_by VARCHAR(255)
);

CREATE TABLE chat(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  chatter_id BIGINT NOT NULL,
  group_id BIGINT NOT NULL,
  message VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_chat_group_id FOREIGN KEY (group_id) REFERENCES chat_group(id),
  CONSTRAINT fk_chat_chatter_id FOREIGN KEY (chatter_id) REFERENCES chatter(id)
);

