INSERT INTO chatters (name, created_by) VALUES ('Alice', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Bob', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Charlie', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('David', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Eve', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Frank', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Grace', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Heidi', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Ivan', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Judy', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Kyle', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Laura', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Mike', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Niaj', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Olivia', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Peggy', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Quinn', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Ryan', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Sybil', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Trent', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Ursula', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Victor', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Wendy', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Xavier', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Yara', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Zane', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Amy', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Ben', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Cathy', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Dan', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Ella', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Finn', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Gina', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Hank', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Ivy', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Jake', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Kara', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Leo', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Mia', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Noel', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Owen', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Pam', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Quentin', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Ruth', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Sam', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Tina', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Uri', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Vera', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Will', 'SYSTEM');
INSERT INTO chatters (name, created_by) VALUES ('Zara', 'SYSTEM');


INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Alpha', 'General discussion group', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Beta', 'Developers hangout', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Gamma', 'Test group for QA', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Delta', 'Random chat room', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Epsilon', 'Secret admin group', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Zeta', 'Photography lovers club', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Echo', 'Gaming community', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Omega', 'Archive & logs group', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Tech', 'Tech talk & debates', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Fun', 'Memes and more', 'SYSTEM');


INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (1, 1, 'creator', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (2, 1, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (3, 1, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (4, 1, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (5, 1, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (6, 1, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (7, 1, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (8, 1, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (9, 1, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (10, 1, 'member', FALSE, 'SYSTEM');

INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (6, 2, 'creator', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (7, 2, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (8, 2, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (9, 2, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (10, 2, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (11, 2, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (12, 2, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (13, 2, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (14, 2, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (15, 2, 'member', FALSE, 'SYSTEM');

INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (11, 3, 'creator', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (12, 3, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (13, 3, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (14, 3, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (15, 3, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (16, 3, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (17, 3, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (18, 3, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (19, 3, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (20, 3, 'member', FALSE, 'SYSTEM');

INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (16, 4, 'creator', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (17, 4, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (18, 4, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (19, 4, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (20, 4, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (21, 4, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (22, 4, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (23, 4, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (24, 4, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (25, 4, 'member', FALSE, 'SYSTEM');

INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (21, 5, 'creator', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (22, 5, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (23, 5, 'admin', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (24, 5, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (25, 5, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (26, 5, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (27, 5, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (28, 5, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (29, 5, 'member', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (30, 5, 'member', FALSE, 'SYSTEM');
