INSERT INTO chatter (name, user_id, created_by) VALUES ('Alice', 1, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Bob', 2, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Charlie', 3, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('David', 4, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Eve', 5, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Frank', 6, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Grace', 7, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Heidi', 8, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Ivan', 9, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Judy', 10, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Kyle', 11, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Laura', 12, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Mike', 13, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Niaj', 14, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Olivia', 15, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Peggy', 16, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Quinn', 17, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Ryan', 18, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Sybil', 19, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Trent', 20, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Ursula', 21, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Victor', 22, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Wendy', 23, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Xavier', 24, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Yara', 25, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Zane', 26, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Amy', 27, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Ben', 28, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Cathy', 29, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Dan', 30, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Ella', 31, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Finn', 32, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Gina', 33, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Hank', 34, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Ivy', 35, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Jake', 36, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Kara', 37, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Leo', 38, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Mia', 39, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Noel', 40, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Owen', 41, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Pam', 42, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Quentin', 43, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Ruth', 44, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Sam', 45, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Tina', 46, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Uri', 47, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Vera', 48, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Will', 49, 'SYSTEM');
INSERT INTO chatter (name, user_id, created_by) VALUES ('Zara', 50, 'SYSTEM');


INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Alpha', 'General discussion group', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Beta', 'Developers hangout', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Gamma', 'Test group for QA', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Delta', 'Random chat room', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Epsilon', 'Secret admin group', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Zeta', 'Photography lovers club', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Echo', 'Gaming community', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Omega', 'Archive & logs group', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Tech', 'Tech talk & debates', 'SYSTEM');
INSERT INTO chat_group (name, description, created_by) VALUES ('Group_Fun', 'Memes and more', 'SYSTEM');


INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (1, 1, 'CREATOR', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (2, 1, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (3, 1, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (4, 1, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (5, 1, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (6, 1, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (7, 1, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (8, 1, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (9, 1, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (10, 1, 'MEMBER', FALSE, 'SYSTEM');

INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (6, 2, 'CREATOR', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (7, 2, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (8, 2, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (9, 2, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (10, 2, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (11, 2, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (12, 2, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (13, 2, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (14, 2, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (15, 2, 'MEMBER', FALSE, 'SYSTEM');

INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (11, 3, 'CREATOR', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (12, 3, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (13, 3, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (14, 3, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (15, 3, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (16, 3, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (17, 3, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (18, 3, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (19, 3, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (20, 3, 'MEMBER', FALSE, 'SYSTEM');

INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (16, 4, 'CREATOR', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (17, 4, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (18, 4, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (19, 4, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (20, 4, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (21, 4, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (22, 4, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (23, 4, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (24, 4, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (25, 4, 'MEMBER', FALSE, 'SYSTEM');

INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (21, 5, 'CREATOR', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (22, 5, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (23, 5, 'ADMIN', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (24, 5, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (25, 5, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (26, 5, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (27, 5, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (28, 5, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (29, 5, 'MEMBER', FALSE, 'SYSTEM');
INSERT INTO group_member (chatter_id, group_id, access_level, restricted, created_by) VALUES (30, 5, 'MEMBER', FALSE, 'SYSTEM');
