export const messages2 = {
  1: [
    { id: 1, fromMe: false, text: "Hey, what's up?" },
    { id: 2, fromMe: true, text: "All good!" },
  ],
  2: [
    { id: 101, fromMe: false, sender: "Rohan", text: "Check the new update" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
    { id: 102, fromMe: false, sender: "Karan", text: "Looks good!" },
  ],
};
