export const roles = [
  {
    id: 1,
    title: "SUDO",
    active: true,
    rolePermissions: [
      {
        id: 1,
        permissionId: "1",
        title: "PERMISSION_CREATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 2,
        permissionId: "2",
        title: "PERMISSION_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 3,
        permissionId: "3",
        title: "PERMISSION_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 4,
        permissionId: "4",
        title: "PERMISSION_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 5,
        permissionId: "5",
        title: "ROLE_CREATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 6,
        permissionId: "6",
        title: "ROLE_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 7,
        permissionId: "7",
        title: "ROLE_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 8,
        permissionId: "8",
        title: "ROLE_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 9,
        permissionId: "9",
        title: "USER_CREATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 10,
        permissionId: "10",
        title: "USER_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 11,
        permissionId: "11",
        title: "USER_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 12,
        permissionId: "12",
        title: "USER_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 13,
        permissionId: "13",
        title: "POSTMAN_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 14,
        permissionId: "14",
        title: "CHAT_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 15,
        permissionId: "15",
        title: "CHAT_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 16,
        permissionId: "16",
        title: "CHAT_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 17,
        permissionId: "17",
        title: "MESSAGE_SEND",
        active: true,
        activeStatus: true,
      },
      {
        id: 18,
        permissionId: "18",
        title: "MESSAGE_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 19,
        permissionId: "19",
        title: "AUDIT_LOG_READ",
        active: true,
        activeStatus: true,
      },
    ],
  },
  {
    id: 2,
    title: "ADMIN",
    active: true,
    rolePermissions: [
      {
        id: 20,
        permissionId: "1",
        title: "PERMISSION_CREATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 21,
        permissionId: "2",
        title: "PERMISSION_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 22,
        permissionId: "3",
        title: "PERMISSION_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 23,
        permissionId: "4",
        title: "PERMISSION_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 24,
        permissionId: "5",
        title: "ROLE_CREATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 25,
        permissionId: "6",
        title: "ROLE_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 26,
        permissionId: "7",
        title: "ROLE_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 27,
        permissionId: "8",
        title: "ROLE_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 28,
        permissionId: "9",
        title: "USER_CREATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 29,
        permissionId: "10",
        title: "USER_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 30,
        permissionId: "11",
        title: "USER_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 31,
        permissionId: "12",
        title: "USER_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 32,
        permissionId: "15",
        title: "CHAT_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 33,
        permissionId: "16",
        title: "CHAT_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 34,
        permissionId: "18",
        title: "MESSAGE_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 35,
        permissionId: "19",
        title: "AUDIT_LOG_READ",
        active: true,
        activeStatus: true,
      },
    ],
  },
  {
    id: 3,
    title: "MANAGER",
    active: true,
    rolePermissions: [
      {
        id: 36,
        permissionId: "6",
        title: "ROLE_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 37,
        permissionId: "9",
        title: "USER_CREATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 38,
        permissionId: "10",
        title: "USER_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 39,
        permissionId: "11",
        title: "USER_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 40,
        permissionId: "12",
        title: "USER_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 42,
        permissionId: "14",
        title: "CHAT_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 43,
        permissionId: "17",
        title: "MESSAGE_SEND",
        active: true,
        activeStatus: true,
      },
      {
        id: 44,
        permissionId: "18",
        title: "MESSAGE_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 41,
        permissionId: "13",
        title: "POSTMAN_UPDATE",
        active: true,
        activeStatus: true,
      },
    ],
  },
  {
    id: 4,
    title: "MODERATOR",
    active: true,
    rolePermissions: [
      {
        id: 45,
        permissionId: "10",
        title: "USER_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 46,
        permissionId: "14",
        title: "CHAT_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 47,
        permissionId: "15",
        title: "CHAT_UPDATE",
        active: true,
        activeStatus: true,
      },
      {
        id: 48,
        permissionId: "16",
        title: "CHAT_DELETE",
        active: true,
        activeStatus: true,
      },
      {
        id: 49,
        permissionId: "18",
        title: "MESSAGE_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 50,
        permissionId: "19",
        title: "AUDIT_LOG_READ",
        active: true,
        activeStatus: true,
      },
    ],
  },
  {
    id: 5,
    title: "CHATTER",
    active: true,
    rolePermissions: [
      {
        id: 51,
        permissionId: "10",
        title: "USER_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 53,
        permissionId: "14",
        title: "CHAT_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 54,
        permissionId: "17",
        title: "MESSAGE_SEND",
        active: true,
        activeStatus: true,
      },
      {
        id: 55,
        permissionId: "18",
        title: "MESSAGE_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 52,
        permissionId: "13",
        title: "POSTMAN_UPDATE",
        active: true,
        activeStatus: true,
      },
    ],
  },
  {
    id: 6,
    title: "CUSTOMER",
    active: true,
    rolePermissions: [
      {
        id: 56,
        permissionId: "10",
        title: "USER_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 57,
        permissionId: "14",
        title: "CHAT_READ",
        active: true,
        activeStatus: true,
      },
      {
        id: 58,
        permissionId: "18",
        title: "MESSAGE_READ",
        active: true,
        activeStatus: true,
      },
    ],
  },
];
