export const users = [
  {
    id: "1",
    name: "Sudo Master",
    userName: "sudo",
    email: "sudo@devops.com",
    emailVerified: true,
    gender: "MALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "6",
        title: "CUSTOMER",
      },
      {
        id: "1",
        title: "SUDO",
      },
      {
        id: "2",
        title: "ADMIN",
      },
      {
        id: "5",
        title: "CHATTER",
      },
      {
        id: "3",
        title: "MANAGER",
      },
      {
        id: "4",
        title: "MODERATOR",
      },
    ],
  },
  {
    id: "2",
    name: "Admin Lead",
    userName: "admin",
    email: "admin@company.com",
    emailVerified: true,
    gender: "MALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "2",
        title: "ADMIN",
      },
      {
        id: "3",
        title: "MANAGER",
      },
      {
        id: "4",
        title: "MODERATOR",
      },
    ],
  },
  {
    id: "3",
    name: "Admin Assistant",
    userName: "admin2",
    email: "admin2@company.com",
    emailVerified: true,
    gender: "FEMALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "2",
        title: "ADMIN",
      },
      {
        id: "3",
        title: "MANAGER",
      },
      {
        id: "4",
        title: "MODERATOR",
      },
    ],
  },
  {
    id: "4",
    name: "Manager One",
    userName: "manager",
    email: "manager@team.com",
    emailVerified: false,
    gender: "MALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "3",
        title: "MANAGER",
      },
      {
        id: "5",
        title: "CHATTER",
      },
    ],
  },
  {
    id: "5",
    name: "Manager Two",
    userName: "manager2",
    email: "manager2@team.com",
    emailVerified: true,
    gender: "FEMALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "3",
        title: "MANAGER",
      },
      {
        id: "5",
        title: "CHATTER",
      },
    ],
  },
  {
    id: "6",
    name: "Moderator Pro",
    userName: "moderator",
    email: "mod@chatapp.com",
    emailVerified: true,
    gender: "MALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "5",
        title: "CHATTER",
      },
      {
        id: "4",
        title: "MODERATOR",
      },
    ],
  },
  {
    id: "7",
    name: "Junior Moderator",
    userName: "mod_junior",
    email: "junior@chatapp.com",
    emailVerified: false,
    gender: "MALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "5",
        title: "CHATTER",
      },
      {
        id: "4",
        title: "MODERATOR",
      },
    ],
  },
  {
    id: "8",
    name: "Active Chatter",
    userName: "chatter",
    email: "chatter1@users.com",
    emailVerified: false,
    gender: "MALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "5",
        title: "CHATTER",
      },
    ],
  },
  {
    id: "9",
    name: "Casual Chatter",
    userName: "chatter2",
    email: "chatter2@users.com",
    emailVerified: true,
    gender: "FEMALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "5",
        title: "CHATTER",
      },
    ],
  },
  {
    id: "10",
    name: "New Chatter",
    userName: "chatter_new",
    email: "new@users.com",
    emailVerified: false,
    gender: "MALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: false,
    roles: [
      {
        id: "5",
        title: "CHATTER",
      },
    ],
  },
  {
    id: "11",
    name: "Premium Customer",
    userName: "customer",
    email: "premium@customers.com",
    emailVerified: false,
    gender: "FEMALE",
    accountNonExpired: true,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "6",
        title: "CUSTOMER",
      },
    ],
  },
  {
    id: "12",
    name: "Standard Customer",
    userName: "customer2",
    email: "standard@customers.com",
    emailVerified: true,
    gender: "MALE",
    accountNonExpired: true,
    accountNonLocked: false,
    enabled: true,
    roles: [
      {
        id: "6",
        title: "CUSTOMER",
      },
    ],
  },
  {
    id: "13",
    name: "Trial Customer",
    userName: "customer_trial",
    email: "trial@customers.com",
    emailVerified: false,
    gender: "FEMALE",
    accountNonExpired: false,
    accountNonLocked: true,
    enabled: true,
    roles: [
      {
        id: "6",
        title: "CUSTOMER",
      },
    ],
  },
];
