INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (1, 2, 'Hello, this is a simple test message 1', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (2, 1, 'Hey! Got your message.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (3, 1, 'What’s happening today?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (1, 3, 'Just testing the chat system.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (4, 2, 'Meeting at 5 PM okay?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (2, 4, 'Yep, that works for me.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (5, 1, 'Can you review my PR?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (1, 5, 'Sure, give me 10 minutes.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (3, 4, 'Did you check the logs?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (4, 3, 'Yes, everything looks fine.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (6, 1, 'New user joined the group.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (1, 6, 'Great! Welcome them.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (7, 2, 'Server is down again.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (2, 7, 'Restarting now.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (8, 3, 'Lunch break?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (3, 8, 'Let’s go!', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (9, 4, 'Deploy scheduled at 8 PM', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (4, 9, 'Roger that.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (10, 5, 'Code looks good.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (5, 10, 'Thanks!', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (1, 7, 'Ping when ready.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (7, 1, 'Ready now.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (2, 5, 'Send me the file.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (5, 2, 'On the way.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (3, 9, 'We need more test data.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (9, 3, 'I will generate some.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (4, 10, 'What task are you working on?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (10, 4, 'Chat module.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (8, 6, 'System running smooth.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (6, 8, 'Good to hear.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (1, 9, 'API response seems slow.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (9, 1, 'Investigating.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (2, 8, 'Check Redis cluster.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (8, 2, 'Okay, doing it now.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (3, 10, 'Push your changes?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (10, 3, 'Done.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (6, 4, 'UI needs improvement.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (4, 6, 'Agreed.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (7, 10, 'Coffee break?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (10, 7, 'Let’s go.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (11, 12, 'Project status update needed by Friday.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (12, 11, 'I will compile the report by then.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (13, 14, 'Remember to commit your code tonight.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (14, 13, 'Just pushed the final changes.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (15, 16, 'Did you get the email about the retreat?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (16, 15, 'Yes, looks like fun!', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (17, 18, 'Let’s pair program on the new module.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (18, 17, 'Great idea, sending invite now.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (19, 20, 'Need to optimize the database query.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (20, 19, 'I have added an index, check performance now.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (21, 22, 'The documentation is outdated.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (22, 21, 'Working on updating it ASAP.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (23, 24, 'What kind of music are you into?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (24, 23, 'Mostly rock and classical.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (25, 26, 'The client presentation is tomorrow.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (26, 25, 'Ready and rehearsed!', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (27, 28, 'Error in line 42, please fix.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (28, 27, 'Fixed and redeploying.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (29, 30, 'Any plans for the weekend?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (30, 29, 'Going hiking.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (31, 32, 'Can we discuss the budget?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (32, 31, 'Sure, book a time on my calendar.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (33, 34, 'Did the new marketing campaign launch?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (34, 33, 'It launched successfully this morning.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (35, 36, 'Need your help with the backend service.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (36, 35, 'I’ll jump on it right away.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (37, 38, 'The test coverage is still low.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (38, 37, 'Adding more unit tests now.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (39, 40, 'Where is the latest artifact stored?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (40, 39, 'Check the main build pipeline output.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (41, 42, 'Feedback on the UI prototype?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (42, 41, 'Looks clean and intuitive.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (43, 44, 'Have you seen the new game trailer?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (44, 43, 'Looks epic!', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (45, 46, 'System performance is spiking.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (46, 45, 'Investigating the resource usage now.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (47, 48, 'Shall we order pizza for the team?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (48, 47, 'Definitely, what kind?', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (49, 50, 'Please finalize the contract details.', 'SYSTEM');
INSERT INTO simple_chat (sender_id, reciever_id, message, created_by) VALUES (50, 49, 'Sending the final draft in 1 hour.', 'SYSTEM');


INSERT INTO group_chat (group_member_id, message, created_by) VALUES (1, 'Hello everyone, welcome to Group_Alpha!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (2, 'Good morning team. Deployment status check?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (3, 'Any updates on the latest QA findings?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (4, 'Deployment is scheduled for 8 PM tonight.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (5, 'Great, thanks for the heads up on the schedule!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (6, 'Group_Beta here: Can someone review my pull request?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (7, 'I will check the Group_Beta PR in 10 minutes.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (8, 'Server running stable now in Group_Beta.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (9, 'Let’s take a short break, back in 15.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (10, 'Back online, what did I miss in Group_Alpha?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (11, 'Welcome to Group_Gamma! Please share your test cases.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (12, 'Group_Gamma needs more test data. I will generate some.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (13, 'Anyone seen the latest random picture in Group_Delta?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (14, 'Project status update needed by Friday.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (15, 'I will compile the report by then.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (16, 'Remember to commit your code tonight.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (17, 'Just pushed the final changes to the main branch.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (18, 'Did you get the email about the retreat?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (19, 'Yes, looks like a fun event!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (20, 'Let’s pair program on the new feature.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (21, 'Group_Epsilon is for admins only. Confidentiality is key.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (22, 'Group_Epsilon: Reviewing security logs now.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (23, 'Need to optimize the database query.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (24, 'I have added an index, check performance now.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (25, 'The Group_Alpha documentation is outdated.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (26, 'Group_Zeta: Share your best landscape shots!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (27, 'Working on updating Group_Zeta guide ASAP.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (28, 'What kind of cameras are people using?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (29, 'Mostly DSLRs and mirrorless.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (30, 'The client presentation is tomorrow.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (31, 'Ready and rehearsed!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (32, 'Error in line 42, please fix.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (33, 'Fixed and redeploying the fix.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (34, 'Any plans for the weekend in Group_Gamma?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (35, 'Going hiking.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (36, 'Can we discuss the budget?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (37, 'Sure, book a time on my calendar.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (38, 'Did the new marketing campaign launch?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (39, 'It launched successfully this morning.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (40, 'Need your help with the backend service.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (41, 'Group_Tech discussion: Microservices vs Monolith?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (42, 'I’ll jump on it right away.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (43, 'The test coverage is still low.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (44, 'Adding more unit tests now.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (45, 'Where is the latest artifact stored?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (46, 'Check the main build pipeline output.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (47, 'Feedback on the UI prototype?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (48, 'Looks clean and intuitive.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (49, 'Have you seen the new game trailer in Group_Echo?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (50, 'Looks epic!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (10, 'System performance is spiking, check Group_Omega logs.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (11, 'Investigating the resource usage now.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (12, 'Shall we order pizza for the team?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (13, 'Definitely, what kind?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (14, 'Please finalize the contract details.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (15, 'Sending the final draft in 1 hour.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (16, 'Anyone got a good meme for Group_Fun?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (17, 'I am stuck on a CSS issue.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (18, 'Try flexbox!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (19, 'We need to deploy the hotfix immediately.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (20, 'The new API endpoint is ready for testing.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (21, 'Just saw a beautiful sunset, sharing in Group_Zeta.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (22, 'Can someone summarize the meeting notes?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (23, 'Meeting notes summarized and attached.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (24, 'Need to schedule a follow-up call.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (25, 'Found a critical vulnerability.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (26, 'Patching system now. Group_Omega notified.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (27, 'Who is free for a brainstorming session?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (28, 'I can join in half an hour.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (29, 'Group_Tech: Thoughts on Rust language?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (30, 'Rust is great for performance!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (31, 'Just achieved a new high score in Group_Echo!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (32, 'Congrats!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (33, 'The database migration script failed.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (34, 'Rolling back changes.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (35, 'Need some fresh ideas for the next sprint.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (36, 'Let’s look at user feedback.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (37, 'Group_Fun: What’s your favorite movie quote?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (38, 'We need to reduce latency.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (39, 'Optimizing cache configuration.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (40, 'The new server rack is installed.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (41, 'Group_Beta: Reviewing the new test environment setup.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (42, 'This feature requires a dependency update.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (43, 'Handling the update now.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (44, 'Please remember team lunch is on Wednesday.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (45, 'Group_Tech: Should we switch to GraphQL?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (46, 'GraphQL has many benefits, let’s discuss.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (47, 'Found the root cause of the outage.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (48, 'Implementing a permanent fix.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (49, 'Group_Echo event tonight, 7 PM!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (50, 'I will be there!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (39, 'Need to clean up the unused code in Group_Gamma.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (40, 'Starting the refactoring process.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (41, 'Group_Omega: All logs have been archived.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (42, 'Thank you for archiving.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (43, 'Is everyone happy with the current sprint velocity?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (44, 'We can aim higher!', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (45, 'Group_Delta: What’s for dinner?', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (46, 'I am thinking pasta.', 'SYSTEM');
INSERT INTO group_chat (group_member_id, message, created_by) VALUES (47, 'Remember to backup the database', 'SYSTEM');
                                                                      
                                                                      
                                                                      
